### ISSUE TITLE
Feature: Default name on hotfix or release using semver

### ISSUE THREAD

**Issue by afranioce** [Shaggy13spe/gitflow4code#15]
Add feature to create new hotfix ou release set name default to use semver [semver](https://semver.org/).

**Comment by Shaggy13spe** [comment]
Hello, sorry for taking so long to look at this feature request. I started down the path of working this in, but now I'm trying to figure out how this would work exactly. In order for me to know what your current version is, I'd have to store it somewhere (which would be in your user settings for this extension), so that it could be read in order to figure out what the name of the branch would be. Furthermore, you would then have to commit this file so that if others create a release branch have the same functionality. Which then means everyone shares the same user settings. Which isn't really ideal. Wanted to give you a chance to explain it more in case I'm reading too much into your request.

**Comment by Shaggy13spe** [comment]
No further response from issuer. Closing
