### ISSUE TITLE
Question: Is it needed to store data in settings.json

### ISSUE THREAD

**Issue by yordan-kanchelov** [Shaggy13spe/gitflow4code#19]
I am wondering what is the purpose of saving the created feature branch and the base from it? What should happen if settings.json is deleted and you decide to finish the feature?

**Comment by Luizgpp** [comment]
Same here. Can i add to .gitignore?

**Comment by Shaggy13spe** [comment]
Sorry, been so wrapped up in two projects at work that I haven't had a chance to devote to this repo. At any rate, much like the git extension, git-flow-avh, information about the feature branch is stored so that it can be correctly finished. Unfortunately, unlike that git extension, VS Code saves to the settings file, which as you point out could accidentally be deleted. However, that goes against what the settings .json file is supposed to be used for when using 3rd party extensions. At any rate, in order to finish a feature in to a branch (any branch, develop or otherwise), you must know where that branch was based from. Getting this information via git is laborious and sometimes prone to error, hence the reason I save it in the settings file. If you don't explicitly give a branch to finish in to (effectively behind the scenes, you are doing a merge, so the branch that is being merged in to must be checked out), it will be finished in to develop, as it would not know that you based from another.
