### ISSUE TITLE
Settings for default values for release and hotfixes branches

### ISSUE THREAD

**Issue by st-schneider** [Shaggy13spe/gitflow4code#3]
It is currently possible to have init values for develop and master but only prefixes for releases or hotfixes. So the base branches need a manual selection.
Would it be possible to implement init values for those branches as well?

**Comment by Shaggy13spe** [comment]
Sorry, not sure what exactly you are asking. Could you explain with an example. The init function currently works the way the giflow-avh does. You are naming the development and production branch and then also the prefixes as you call them (but in essence the branch names) for feature, hotfix and release branches. Hotfix branches always use the production branch as their base, and Release always uses the development branch. Feature branches have an option when being created to base off of development or to pick another branch as its base.

**Comment by st-schneider** [comment]
Sorry for the misunderstanding. I basically meant if it is possible to implement default base branches for develop/master/feature/release/hotfix like in https://github.com/petervanderdoes/gitflow-avh#creating-featurereleasehotfixsupport-branches.
From the src I think you started to do that for the feature branches already with the additional features config.

**Comment by Shaggy13spe** [comment]
Ok, I see what you are saying. As a general rule the default base branch, should always be as follows: features & releases base off of whatever you deem as the development branch, whereas hotfixes base off of whatever you deem as your production branch. I have the functionality to pick another branch other than development for features, but did not implement such functionality for release & hotfixes. I can add that functionality for those two as well, but still believe the default should always be either development (for feature/releases) or production (for hotfixes). This follows the same guidelines available in gitflow-avh. Would this work for your case?

**Comment by st-schneider** [comment]
That would be great, since we have a slightly different workflow and would need other bases.

**Comment by Shaggy13spe** [comment]
So I'd like to get your feedback. Trying to figure out if I should just allow feature/release/hotfix branches to based off any defined branch, or if I should impose some sort of logic to it, like features wouldn't ever be pulled from a production, release, or hotfix branch, because they are active development (which is current working functionality), releases wouldn't really be pulled from a production or hotfix branch, because they are a rollup of work done in the development branch ready to merged to production, and so on. I feel this keeps the extension in the spirit of the feature workflow as outlined by Vic Driessen, while allowing for some flexibility that was added by Peter in gitflow-avh. However, while that may help to keep things a little more clean and keep some people from accidentally creating branches from where they really shouldn't be, I do see that it might hamstring some who are using the extension but not really using the feature workflow at all as prescribed by gitflow. So to that end, based on your workflow, would my original proposal not work? I'd like to keep the spirit of gitflow intact (as that is the name of the extension) while making it as easy to use and as useful for the most people as possible.

**Comment by st-schneider** [comment]
For my current workflow I would just have to manually select a different base when creating branches. So for me it would be a benefit if I could configure other default branches. Sometimes it simply starts with naming things i.e. our 'development' branch is not called 'develop' and so on.

**Comment by Shaggy13spe** [comment]
Ok, I will then just leave it wide open as to what branch someone wants to base from, which is really what giflow-avh allows. BTW, not sure if you realize, you can change the defaults used by the extension. The easiest way is obviously if you haven't already initialized your repo because the extension has the option to initialize with custom names/prefixes. However, if you have already initialized prior to using the extension, you can edit the properties for gitflow4code.init in your User Settings file.
// Initialization values for git flow branches
  "gitflow4code.init": {
    "develop": "develop",
    "master": "master",
    "features": "feature/",
    "releases": "release/",
    "hotfixes": "hotfix/"
  }

**Comment by st-schneider** [comment]
I know but, I also have a release and hotfix branch which might have different base branches. And I can only make a prefix in this case.

**Comment by Shaggy13spe** [comment]
Ok, new version 1.1.0 available. Fully opens up the ability to base features, releases, and hotfixes off of any branch the user may want.

**Comment by st-schneider** [comment]
Am I able to configure the bases for those branches as well?

**Comment by Shaggy13spe** [comment]
Not sure I understand. Can you give me an example of your workflow so I can help you further? As it is now, the extension will let you choose any branch to base features, releases, and hotfixes from. If you want to configure what your "development", or "production" branch is named (which would also be the default branches for features/release and hotfixes, respectively, you can do so in the User Settings). This is also where you can configure the prefixes used when creating the feature, release, or hotfix branches.

**Comment by st-schneider** [comment]
```
/* gitflow */
  "gitflow4code.init": {
    "develop": "stage",
    "master": "live",
    "features": "",
    "releases": "release/",
    "hotfixes": "hotfix/"
  }
```
where can I set the default branch for features/releases/hotfixes?

**Comment by Shaggy13spe** [comment]
Ok, I think I understand now. As of now, there is no way to configure defaults for features/releases/hotfixes other than the defaults as outlined by gitflow which is features & releases always use whatever you define as the develop branch (stage in your case) and hotfixes the master branch (live in your case). If you want to use something other than the default, that is where my latest changes would allow for you to choose a new base, but as far as saving a new default separate than the develop/master defined in the config file, no that is not supported. It seems like it would be an edge case, because at that point, you are not using the gitflow workflow, which is what the extension is actually trying to nudge you in to.
