### ISSUE TITLE
Prefix 'feature' was added when it shouldn't

### ISSUE THREAD

**Issue by st-schneider** [Shaggy13spe/gitflow4code#5]
I made a started a new feature and chose a custom base. I have no prefix set for feature, not in .git/conifg nor in usersetting gitflow4code.init.feature but feature/ was added to the branch name.

**Comment by Shaggy13spe** [comment]
There are several places in the code that I do sanity checks to make sure a feature is actually the current branch and this is based on the prefix. Changing the code to allow for blank will cause more problems than I care to address, however, a workaround would be in your user settings.json file, you should be able to just clear the features value and it shouldn't prefix them anymore. If this isn't working, then try restarting VSCode, because the extension is caching the settings upon start up it seems.
