### ISSUE TITLE
Ability to show/hide status bar finish feature button

### ISSUE THREAD

**Issue by kristiannotari** [Shaggy13spe/gitflow4code#6]
Hi, I've been using this extension for almost a month now and it works very well. I appreciate your work because it simplifies my workflow. But since I also use other extensions, my bottom status bar used to look messy way before the last update, and I didn't find any command to hide your new `finish type/branch` button, I wonder if it could be optional in the next update.

<img width="513" alt="image" src="https://user-images.githubusercontent.com/17885006/39409378-423c1ff0-4be6-11e8-8e10-05d5a3bfde5f.png">

Thanks,
Kristian

**Comment by Shaggy13spe** [comment]
Hello, I'm glad to hear that the extension is working well for you. This is definitely something I can add to the next update. I've noticed a few issues with the button not refreshing itself and so I can slip it in to the fix I have working for that. Also, in case you weren't aware, I added keyboard shortcuts in the last update for those of us who like them over the mouse. ;)

**Comment by kristiannotari** [comment]
Great to hear you this quick!

If I should be honest with you, I noticed the shortcuts, but since, at least for my workflow, they are not so frequent operations, I prefer to leave them the right space. When I need to manage git flow workflow, then I need to think about what I’m doing, taking my time, then execute what I want. This was perfect with your single entry point, which then spread over nested options. Every step I was making, I was thinking about what I was doing. This was preferable, but this is, maybe, just my case.

Not for bothering you but, do you know when the next update will turn out? :)

**Comment by Shaggy13spe** [comment]
don't have an exact date, but shouldn't be too long. maybe a week or two. Just wondering also, if you could be so kind as to give a review of the extension on the marketplace, as well as telling others of it. Thanks!

**Comment by Shaggy13spe** [comment]
Ok, I couldn't reproduce the issues I was seeing with the button on my other machine, so thinking it may have been a development artifact. At any rate, made it easier to go ahead and add that option. Just published 1.2.1 with it in there. :)

**Comment by kristiannotari** [comment]
Done!

Please, thinks a moment about the previous command system with a single entry point. I really preferred that ;)

**Comment by Shaggy13spe** [comment]
While I appreciate the preference for the original single command, I had originally created this extension for the several teams I manage at my company, and there number one ask since then was to allow for quicker access to the commands (starting, finishing, etc) which means that the single command had to go. Because you can't assign shortcuts to anything but a command (what is available in the command pallet Cmd+P), nor can status bar buttons work on anything that isn't a command. i have put a question out if it is possible to "conditionalize" the command list, but based on how extensions are built (using the package.json  and not code to define commands), I don't see how that is possible

**Comment by kristiannotari** [comment]
Now it’s clear! Thanks for the explanation.
