### ISSUE TITLE
Is repository really git flow initialized?

### ISSUE THREAD

**Issue by kristiannotari** [Shaggy13spe/gitflow4code#8]
Maybe I'm doing something wrong, but I gitflow initialized a repository with your command then used it without any problems (still with your commands).

But when I try to use pure command line gitflow avh commands, then it tells me this is not a git flow repository.

Something wrong or expected behavior?

**Comment by Shaggy13spe** [comment]
Sorry, been on vacation. So my extension, while based on gitflow-avh, does not actually use gitflow-avh. I removed it because I didn't want users to have to install something else to be able to use my extension. Because of this, initializing the repo with my extension uses the VS Code user settings for configuration, whereas gitflow-avh uses the git config file.
